### ISSUE TITLE
Error pulling container

### ISSUE THREAD

**Issue by TCBWZA** [cutzenfriend/docker-absautoconverter#6]
When I use the compose file included below, I get an error stating, "failed to register layer: archive/tar: invalid tar header" . In reading forums, this could be caused by a change to the rootfs, if it is stored as something other than tar.gz. (The suggestion is to rebuild the container on a newer version of docker.) I assume it could also be an upstream corruption. (There are a lot of instances of this affecting Fedora systems, I'm using Ubuntu).

Docker (details below) is running in an LXC container on Proxmox (8.4.1) on an AMD APU. 

```
Client: Docker Engine - Community
 Version:           28.1.1
 API version:       1.49
 Go version:        go1.23.8
 Git commit:        4eba377
 Built:             Fri Apr 18 09:52:57 2025
 OS/Arch:           linux/amd64
 Context:           default

```

Do you have any suggestions as to what I can try do to resolve this?

```
services:
  abs-autoconverter:
    image: cutzenfriend/abs-autoconverter:latest
    container_name: abs-autoconverter
    restart: unless-stopped
    environment:
      TZ: "Europe/Berlin"
      DOMAIN: "MyDomain" #Please edit - mandatory
      LIBRARY_ID: "MyLIB" #Please edit - mandatory
      MAX_PARALLEL_CONVERSIONS: 1 #Keep CPU power in mind. Too many conversion in parallel decrease performance on your host!
      #CRON_SETTING: "(11,22,33,44,55 * * * * )" #optional - default is: (11,22,33,44,55 * * * * ) - every hour at minute 20
      BITRATE: "128k" #optional - default is: 128k
      TOKEN: "MyToken" #Please edit - mandatory
```
